port: 3000
client: http://localhost:5173
salt: 10

jwt:
  secret-key: hehe
  access-token-expire-in: 10s
  refresh-token-expire-in: 7d

facebook:
  client-id: 1213240936224087
  client-secret: c5eb7ba9c91525de7e980e1d15786555
  graph-url: https://graph.facebook.com

postgres:
  username: postgres
  password: postgres
  name: database
  host: localhost
  port: 5432
  dialect: postgres

cloudinary:
  cloud-name: dzd6xmzvv
  api-key: 156269933569375
  api-secret: 3f_Nhoy9S7uk_sJuUQyYBD0pGkQ
