port: 3000
client: http://localhost:5173
salt: 10

jwt:
  secret-key: hehe
  access-token-expire-in: 10
  refresh-token-expire-in: 604800

facebook:
  client-id: 1213240936224087
  client-secret: c5eb7ba9c91525de7e980e1d15786555
  graph-url: https://graph.facebook.com

postgres:
  username: 'postgres'
  password: 'postgres'
  name: 'database'
  host: 'localhost'
  port: 5432
  dialect: 'postgres'

cloudinary:
  cloud-name: 'dzd6xmzvv'
  api-key: '156269933569375'
  api-secret: '3f_Nhoy9S7uk_sJuUQyYBD0pGkQ'

redis:
  host: 127.0.0.1
  port: 6379

google:
  client-id: 582703940307-qgduv26gmp8ie39i759v6n48k13n40dt.apps.googleusercontent.com
  client-secret: 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
  token: 1//04kE-IFY7Gh52CgYIARAAGAQSNgF-L9Ir5azrdQnJnt9dnLoERXQiyVRv_JFNv0KMX12LoYCmLB-LgKdUltbpHJNY9dAZQJVS1Q
  oauth2-callback-url: https://developers.google.com/oauthplayground

otp:
  ttl: 1800
