port: 3000
client_host: 'http://localhost:5173'

jwt:
  secret_key: 'hehe'
  access_expire_in: '1m'
  refresh_expire_in: '7d'

facebook:
  client_id: '1213240936224087'
  client_secret: 'c5eb7ba9c91525de7e980e1d15786555'
  callback_url: 'http://localhost:3000/auth/facebook/callback'
  graph_url: 'https://graph.facebook.com'
  access_expire_in: '5h'
