port: 3000
client: http://localhost:5173

jwt:
  secret-key:
  access-token-expire-in:
  refresh-token-expire-in:

facebook:
  client-id:
  client-secret:
  callback-url:
  graph-url:

postgres:
  username:
  password:
  name:
  host:
  port:
  dialect:
